CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE TABLE departments (
        "Id" uuid NOT NULL,
        "Code" character varying(50) NOT NULL,
        "CenterName" character varying(200) NOT NULL,
        "DepartmentOrWorkshopName" character varying(200) NOT NULL,
        "TeamName" character varying(200),
        "GroupName" character varying(200),
        "Notes" character varying(1000),
        "Status" integer NOT NULL,
        "CreatedAtUtc" timestamp without time zone NOT NULL,
        "UpdatedAtUtc" timestamp without time zone,
        CONSTRAINT "PK_departments" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE TABLE device_cmd (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "DeviceSn" character varying(50),
        "Content" text,
        "CommitTime" timestamp without time zone,
        "TransTime" timestamp without time zone,
        "ResponseTime" timestamp without time zone,
        "ReturnValue" text,
        "Description" character varying(1000),
        CONSTRAINT "PK_device_cmd" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE TABLE devices (
        "Id" uuid NOT NULL,
        "Code" character varying(100) NOT NULL,
        "Name" character varying(250) NOT NULL,
        "SerialNumber" character varying(50),
        "IpAddress" character varying(50),
        "MacAddress" character varying(50),
        "Port" integer,
        "Location" character varying(500),
        "ActivationCode" character varying(200),
        "VendorName" character varying(100),
        "DeviceModel" character varying(200),
        "FirmwareVersion" character varying(100),
        "FingerprintVersion" character varying(100),
        "TimeZone" character varying(50),
        "Status" integer NOT NULL,
        "IsInUse" boolean NOT NULL,
        "UserCount" integer NOT NULL,
        "AttendanceLogCount" integer NOT NULL,
        "FingerprintCount" integer NOT NULL,
        "AttendanceLogStamp" character varying(100),
        "AttendancePhotoStamp" character varying(100),
        "OperationLogStamp" character varying(100),
        "ErrorLogStamp" character varying(100),
        "TransferFlag" character varying(1000),
        "Delay" character varying(100),
        "Realtime" character varying(20),
        "TransInterval" character varying(100),
        "TransTimes" character varying(100),
        "Encrypt" character varying(20),
        "ErrorDelay" character varying(100),
        "Timeout" integer,
        "SyncTime" integer NOT NULL,
        "LastRequestTime" timestamp without time zone,
        "IrTempDetectionFunOn" character varying(20),
        "MaskDetectionFunOn" character varying(20),
        "MultiBioDataSupport" character varying(200),
        "CreatedAtUtc" timestamp without time zone NOT NULL,
        "UpdatedAtUtc" timestamp without time zone,
        CONSTRAINT "PK_devices" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE TABLE errorlog (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ErrCode" text,
        "ErrMsg" text,
        "DataOrigin" text,
        "CmdId" character varying(100),
        "Additional" text,
        "DeviceId" character varying(50),
        CONSTRAINT "PK_errorlog" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE TABLE oplog (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Operator" character varying(500),
        "OpTime" timestamp without time zone,
        "OpType" character varying(500),
        "User" character varying(50),
        "Obj1" character varying(500),
        "Obj2" character varying(500),
        "Obj3" character varying(500),
        "Obj4" character varying(500),
        "DeviceId" character varying(500),
        CONSTRAINT "PK_oplog" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE TABLE outbound_attendance_logs (
        "Id" uuid NOT NULL,
        "AttendanceLogId" uuid NOT NULL,
        "DeviceSn" character varying(50) NOT NULL,
        "EmployeeCode" character varying(50) NOT NULL,
        "TapTime" timestamp without time zone NOT NULL,
        "VerificationMode" integer NOT NULL,
        "InOutMode" integer NOT NULL,
        "AttemptCount" integer NOT NULL,
        "Status" character varying(20) NOT NULL,
        "LastError" text,
        "CreatedAtUtc" timestamp without time zone NOT NULL,
        "UpdatedAtUtc" timestamp without time zone NOT NULL,
        "LastAttemptAtUtc" timestamp without time zone,
        "NextAttemptAtUtc" timestamp without time zone,
        "DeliveredAtUtc" timestamp without time zone,
        "FailedAtUtc" timestamp without time zone,
        CONSTRAINT "PK_outbound_attendance_logs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE TABLE outbound_system_logs (
        "Id" uuid NOT NULL,
        "DeviceSn" character varying(50) NOT NULL,
        "ConnectionId" character varying(100) NOT NULL,
        "Direction" character varying(20) NOT NULL,
        "EventType" character varying(100) NOT NULL,
        "Message" text NOT NULL,
        "OccurredAtUtc" timestamp without time zone NOT NULL,
        "AttemptCount" integer NOT NULL,
        "Status" character varying(20) NOT NULL,
        "LastError" text,
        "CreatedAtUtc" timestamp without time zone NOT NULL,
        "UpdatedAtUtc" timestamp without time zone NOT NULL,
        "LastAttemptAtUtc" timestamp without time zone,
        "NextAttemptAtUtc" timestamp without time zone,
        "DeliveredAtUtc" timestamp without time zone,
        "FailedAtUtc" timestamp without time zone,
        CONSTRAINT "PK_outbound_system_logs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE TABLE positions (
        "Id" uuid NOT NULL,
        "Code" character varying(50) NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Description" character varying(1000),
        "Status" integer NOT NULL,
        "CreatedAtUtc" timestamp without time zone NOT NULL,
        "UpdatedAtUtc" timestamp without time zone,
        CONSTRAINT "PK_positions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE TABLE employees (
        "Id" uuid NOT NULL,
        "EmployeeCode" character varying(50) NOT NULL,
        "FirstName" character varying(100) NOT NULL,
        "LastName" character varying(150) NOT NULL,
        "Email" character varying(256),
        "PhoneNumber" character varying(30),
        "Avatar" text,
        "HireDate" date NOT NULL,
        "DepartmentId" uuid NOT NULL,
        "PositionId" uuid NOT NULL,
        "Status" integer NOT NULL,
        "CreatedAtUtc" timestamp without time zone NOT NULL,
        "UpdatedAtUtc" timestamp without time zone,
        CONSTRAINT "PK_employees" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_employees_departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES departments ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_employees_positions_PositionId" FOREIGN KEY ("PositionId") REFERENCES positions ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE TABLE attendance_daily_summaries (
        "Id" uuid NOT NULL,
        "EmployeeId" uuid,
        "WorkDate" date NOT NULL,
        "PunchCount" integer NOT NULL,
        "PunchMomentsText" text NOT NULL,
        "FirstPunchTime" timestamp without time zone,
        "LastPunchTime" timestamp without time zone,
        "CreatedAtUtc" timestamp without time zone NOT NULL,
        "UpdatedAtUtc" timestamp without time zone,
        CONSTRAINT "PK_attendance_daily_summaries" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_attendance_daily_summaries_employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES employees ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE TABLE attendance_logs (
        "Id" uuid NOT NULL,
        "DeviceId" uuid NOT NULL,
        "EmployeeId" uuid,
        "AttTime" timestamp without time zone,
        "Status" character varying(10),
        "Verify" character varying(10),
        "WorkCode" character varying(50),
        "Reserved1" character varying(50),
        "Reserved2" character varying(50),
        "DeviceCode" character varying(50),
        "MaskFlag" integer,
        "Temperature" character varying(50),
        "DedupKey" character varying(200) NOT NULL,
        "UpdateTime" timestamp without time zone NOT NULL,
        "CreatedAtUtc" timestamp without time zone NOT NULL,
        "UpdatedAtUtc" timestamp without time zone,
        CONSTRAINT "PK_attendance_logs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_attendance_logs_employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES employees ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE TABLE bio_photos (
        "Id" uuid NOT NULL,
        "EmployeeId" uuid NOT NULL,
        "DeviceSn" character varying(50) NOT NULL,
        "FileName" character varying(255) NOT NULL,
        "Type" character varying(50),
        "Size" integer,
        "Content" text NOT NULL,
        "CreatedAtUtc" timestamp without time zone NOT NULL,
        "UpdatedAtUtc" timestamp without time zone,
        CONSTRAINT "PK_bio_photos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_bio_photos_employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES employees ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE TABLE biodata (
        "Id" uuid NOT NULL,
        "EmployeeId" uuid NOT NULL,
        "DeviceSn" character varying(50) NOT NULL,
        "Pin" character varying(50) NOT NULL,
        "BioNo" character varying(20),
        "BioIndex" character varying(20),
        "Valid" character varying(20),
        "Duress" character varying(20),
        "BioType" character varying(20),
        "MajorVersion" character varying(20),
        "MinorVersion" character varying(20),
        "Format" character varying(20),
        "TemplateData" text NOT NULL,
        "CreatedAtUtc" timestamp without time zone NOT NULL,
        "UpdatedAtUtc" timestamp without time zone,
        CONSTRAINT "PK_biodata" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_biodata_employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES employees ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE TABLE device_user_profiles (
        "Id" uuid NOT NULL,
        "EmployeeId" uuid NOT NULL,
        "EmployeeCode" character varying(50) NOT NULL,
        "DeviceSn" character varying(50) NOT NULL,
        "FullName" character varying(200),
        "Password" character varying(100),
        "CardNumber" character varying(100),
        "GroupCode" character varying(50),
        "TimeZoneCode" character varying(50),
        "PrivilegeCode" character varying(20),
        "VerifyMode" character varying(20),
        "ViceCard" character varying(100),
        "CreatedAtUtc" timestamp without time zone NOT NULL,
        "UpdatedAtUtc" timestamp without time zone,
        CONSTRAINT "PK_device_user_profiles" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_device_user_profiles_employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES employees ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE TABLE face_templates (
        "Id" uuid NOT NULL,
        "EmployeeId" uuid NOT NULL,
        "DeviceSn" character varying(50) NOT NULL,
        "Fid" character varying(20) NOT NULL,
        "Size" integer,
        "Valid" character varying(20),
        "TemplateData" text NOT NULL,
        "Version" character varying(20),
        "CreatedAtUtc" timestamp without time zone NOT NULL,
        "UpdatedAtUtc" timestamp without time zone,
        CONSTRAINT "PK_face_templates" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_face_templates_employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES employees ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE TABLE fingerprint_templates (
        "Id" uuid NOT NULL,
        "EmployeeId" uuid NOT NULL,
        "EmployeeCode" character varying(50) NOT NULL,
        "DeviceSn" character varying(50) NOT NULL,
        "Fid" character varying(20) NOT NULL,
        "Size" integer,
        "Valid" character varying(20),
        "TemplateData" text NOT NULL,
        "MajorVersion" character varying(20),
        "MinorVersion" character varying(20),
        "Duress" character varying(20),
        "CreatedAtUtc" timestamp without time zone NOT NULL,
        "UpdatedAtUtc" timestamp without time zone,
        CONSTRAINT "PK_fingerprint_templates" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_fingerprint_templates_employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES employees ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE TABLE fvein_templates (
        "Id" uuid NOT NULL,
        "EmployeeId" uuid NOT NULL,
        "DeviceSn" character varying(50) NOT NULL,
        "Fid" character varying(20) NOT NULL,
        "Index" character varying(20) NOT NULL,
        "Size" integer,
        "Valid" character varying(20),
        "TemplateData" text NOT NULL,
        "Version" character varying(20),
        "Duress" character varying(20),
        "CreatedAtUtc" timestamp without time zone NOT NULL,
        "UpdatedAtUtc" timestamp without time zone,
        CONSTRAINT "PK_fvein_templates" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_fvein_templates_employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES employees ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE TABLE user_pictures (
        "Id" uuid NOT NULL,
        "EmployeeId" uuid NOT NULL,
        "DeviceSn" character varying(50) NOT NULL,
        "FileName" character varying(255) NOT NULL,
        "Size" integer,
        "Content" text NOT NULL,
        "CreatedAtUtc" timestamp without time zone NOT NULL,
        "UpdatedAtUtc" timestamp without time zone,
        CONSTRAINT "PK_user_pictures" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_user_pictures_employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES employees ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE INDEX "IX_attendance_daily_summaries_EmployeeId" ON attendance_daily_summaries ("EmployeeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_attendance_daily_summaries_EmployeeId_WorkDate" ON attendance_daily_summaries ("EmployeeId", "WorkDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE INDEX "IX_attendance_daily_summaries_WorkDate" ON attendance_daily_summaries ("WorkDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE INDEX "IX_attendance_logs_AttTime" ON attendance_logs ("AttTime");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_attendance_logs_DedupKey" ON attendance_logs ("DedupKey");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE INDEX "IX_attendance_logs_DeviceId" ON attendance_logs ("DeviceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE INDEX "IX_attendance_logs_EmployeeId" ON attendance_logs ("EmployeeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE INDEX "IX_attendance_logs_UpdateTime" ON attendance_logs ("UpdateTime");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_bio_photos_EmployeeId" ON bio_photos ("EmployeeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE INDEX "IX_biodata_EmployeeId" ON biodata ("EmployeeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_biodata_EmployeeId_BioNo_BioIndex_BioType" ON biodata ("EmployeeId", "BioNo", "BioIndex", "BioType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE INDEX ix_device_cmd_commit_time ON device_cmd ("CommitTime");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE INDEX ix_device_cmd_device_sn ON device_cmd ("DeviceSn");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE INDEX ix_device_cmd_response_time ON device_cmd ("ResponseTime");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_device_user_profiles_EmployeeCode" ON device_user_profiles ("EmployeeCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE INDEX "IX_device_user_profiles_EmployeeId" ON device_user_profiles ("EmployeeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE INDEX "IX_employees_DepartmentId" ON employees ("DepartmentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE INDEX "IX_employees_PositionId" ON employees ("PositionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE INDEX "IX_errorlog_CmdId" ON errorlog ("CmdId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE INDEX "IX_errorlog_DeviceId" ON errorlog ("DeviceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE INDEX "IX_face_templates_EmployeeId" ON face_templates ("EmployeeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_face_templates_EmployeeId_Fid" ON face_templates ("EmployeeId", "Fid");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE INDEX "IX_fingerprint_templates_EmployeeCode" ON fingerprint_templates ("EmployeeCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_fingerprint_templates_EmployeeCode_Fid" ON fingerprint_templates ("EmployeeCode", "Fid");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE INDEX "IX_fingerprint_templates_EmployeeId" ON fingerprint_templates ("EmployeeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE INDEX "IX_fvein_templates_EmployeeId" ON fvein_templates ("EmployeeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_fvein_templates_EmployeeId_Fid_Index" ON fvein_templates ("EmployeeId", "Fid", "Index");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE INDEX "IX_oplog_DeviceId" ON oplog ("DeviceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE INDEX "IX_oplog_OpTime" ON oplog ("OpTime");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_outbound_attendance_logs_attendance_log_id ON outbound_attendance_logs ("AttendanceLogId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE INDEX ix_outbound_attendance_logs_created_at ON outbound_attendance_logs ("CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE INDEX ix_outbound_attendance_logs_next_attempt ON outbound_attendance_logs ("NextAttemptAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE INDEX ix_outbound_attendance_logs_status ON outbound_attendance_logs ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE INDEX ix_outbound_system_logs_created_at ON outbound_system_logs ("CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE INDEX ix_outbound_system_logs_next_attempt ON outbound_system_logs ("NextAttemptAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE INDEX ix_outbound_system_logs_status ON outbound_system_logs ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_user_pictures_EmployeeId" ON user_pictures ("EmployeeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624070924_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260624070924_InitialCreate', '10.0.4');
    END IF;
END $EF$;
COMMIT;

