using Microsoft.EntityFrameworkCore;
using Vnta.AttendanceGateway.Data;
using Vnta.AttendanceGateway.Domain;

namespace Vnta.AttendanceGateway.Integration;

public sealed class AttendanceGatewayEmployeeIdentityResolver
{
    private const string UnassignedDepartmentName = "Phòng ban chưa đặt tên";
    private const string UnassignedDepartmentCode = "AUTO-UNASSIGNED-DEPARTMENT";
    private const string UnassignedPositionName = "Chưa xác định chức vụ";
    private const string UnassignedPositionCode = "AUTO-UNASSIGNED-POSITION";
    private const int AutoCreatedReferenceStatus = 0;
    private const int AutoCreatedEmployeeStatus = 2;

    private static readonly string[] AutoGeneratedLastNames =
    [
        "Tự động từ ATTLOG",
        "Tự động từ OPERLOG",
        "Tự động từ BIODATA",
        "-"
    ];

    private readonly ILogger<AttendanceGatewayEmployeeIdentityResolver> _logger;

    public AttendanceGatewayEmployeeIdentityResolver(ILogger<AttendanceGatewayEmployeeIdentityResolver> logger)
    {
        _logger = logger;
    }

    public string NormalizePinToEmployeeCode(string pin)
    {
        return ZktecoEmployeeCode.FromPin(pin);
    }

    public async Task<ZktecoEmployee?> EnsureEmployeeFromPinAsync(
        ZktecoDbContext dbContext,
        IDictionary<string, ZktecoEmployee> employeeLookup,
        string pin,
        string? fullName,
        string sourceLabel,
        DateTime now,
        bool allowAutoCreate,
        CancellationToken cancellationToken)
    {
        var employeeCode = NormalizePinToEmployeeCode(pin);
        if (employeeLookup.TryGetValue(employeeCode, out var cachedEmployee))
        {
            UpdateEmployeeNameIfNeeded(cachedEmployee, fullName, sourceLabel, now);
            return cachedEmployee;
        }

        var existingEmployees = await dbContext.Employees
            .Where(x => x.EmployeeCode == employeeCode)
            .OrderByDescending(x => x.UpdatedAtUtc ?? x.CreatedAtUtc)
            .ThenByDescending(x => x.CreatedAtUtc)
            .ThenByDescending(x => x.Id)
            .Take(2)
            .Select(x => new ExistingEmployeeCandidate
            {
                Id = x.Id,
                EmployeeCode = x.EmployeeCode,
                FirstName = x.FirstName,
                LastName = x.LastName,
                Email = EF.Property<string?>(x, nameof(ZktecoEmployee.Email)),
                PhoneNumber = x.PhoneNumber,
                HireDate = x.HireDate,
                DepartmentId = x.DepartmentId,
                PositionId = x.PositionId,
                Status = x.Status,
                CreatedAtUtc = x.CreatedAtUtc,
                UpdatedAtUtc = x.UpdatedAtUtc
            })
            .ToListAsync(cancellationToken);

        if (existingEmployees.Count > 1)
        {
            _logger.LogWarning(
                "Found duplicate employees while resolving VNTA Attendance Gateway identity. EmployeeCode={EmployeeCode}, SelectedEmployeeId={SelectedEmployeeId}",
                employeeCode,
                existingEmployees[0].Id);
        }

        var existingEmployee = existingEmployees.FirstOrDefault();
        ZktecoEmployee? employee;

        if (existingEmployee is null)
        {
            if (!allowAutoCreate)
            {
                _logger.LogWarning(
                    "Skipping {SourceLabel} payload because employee code does not exist and VNTA Attendance Gateway auto-create is disabled. EmployeeCode={EmployeeCode}, PIN={Pin}",
                    sourceLabel,
                    employeeCode,
                    pin);
                return null;
            }

            employee = await CreateAutoEmployeeAsync(
                dbContext,
                employeeCode,
                fullName,
                sourceLabel,
                now,
                cancellationToken);
        }
        else
        {
            var resolvedEmail = string.IsNullOrWhiteSpace(existingEmployee.Email)
                ? BuildAutoEmployeeEmail(existingEmployee.EmployeeCode)
                : existingEmployee.Email.Trim();

            if (string.IsNullOrWhiteSpace(existingEmployee.Email))
            {
                await dbContext.Employees
                    .Where(x => x.Id == existingEmployee.Id)
                    .ExecuteUpdateAsync(
                        setters => setters
                            .SetProperty(x => x.Email, resolvedEmail)
                            .SetProperty(x => x.UpdatedAtUtc, now),
                        cancellationToken);

                _logger.LogInformation(
                    "Backfilled missing employee email while resolving VNTA Attendance Gateway identity. EmployeeId={EmployeeId}, EmployeeCode={EmployeeCode}, Email={Email}",
                    existingEmployee.Id,
                    existingEmployee.EmployeeCode,
                    resolvedEmail);
            }

            employee = dbContext.Employees.Local.FirstOrDefault(x => x.Id == existingEmployee.Id);
            if (employee is null)
            {
                employee = new ZktecoEmployee
                {
                    Id = existingEmployee.Id,
                    EmployeeCode = existingEmployee.EmployeeCode,
                    FirstName = existingEmployee.FirstName,
                    LastName = existingEmployee.LastName,
                    Email = resolvedEmail,
                    PhoneNumber = existingEmployee.PhoneNumber,
                    HireDate = existingEmployee.HireDate,
                    DepartmentId = existingEmployee.DepartmentId,
                    PositionId = existingEmployee.PositionId,
                    Status = existingEmployee.Status,
                    CreatedAtUtc = existingEmployee.CreatedAtUtc,
                    UpdatedAtUtc = existingEmployee.UpdatedAtUtc
                };

                dbContext.Attach(employee);
            }
            else
            {
                employee.Email = resolvedEmail;
            }

            UpdateEmployeeNameIfNeeded(employee, fullName, sourceLabel, now);
        }

        employeeLookup[employeeCode] = employee;
        return employee;
    }

    public Task EnsureEmployeesForCodesAsync(
        ZktecoDbContext dbContext,
        IDictionary<string, ZktecoEmployee> employeeLookup,
        IReadOnlyCollection<string> employeeCodes,
        string sourceLabel,
        DateTime now,
        CancellationToken cancellationToken)
    {
        if (employeeCodes.Count == 0)
        {
            return Task.CompletedTask;
        }

        var missingEmployeeCodes = employeeCodes
            .Where(x => !employeeLookup.ContainsKey(x))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToArray();

        if (missingEmployeeCodes.Length == 0)
        {
            return Task.CompletedTask;
        }

        _logger.LogWarning(
            "Skipping {SourceLabel} payload employees because VNTA Attendance Gateway auto-create is disabled. MissingEmployeeCodes={MissingEmployeeCodes}",
            sourceLabel,
            string.Join(", ", missingEmployeeCodes));

        return Task.CompletedTask;
    }

    private async Task<ZktecoEmployee> CreateAutoEmployeeAsync(
        ZktecoDbContext dbContext,
        string employeeCode,
        string? fullName,
        string sourceLabel,
        DateTime now,
        CancellationToken cancellationToken)
    {
        var department = await EnsureFallbackDepartmentAsync(dbContext, now, cancellationToken);
        var position = await EnsureFallbackPositionAsync(dbContext, now, cancellationToken);
        var (firstName, lastName) = SplitEmployeeName(fullName, employeeCode, sourceLabel);

        var employee = new ZktecoEmployee
        {
            Id = Guid.CreateVersion7(),
            EmployeeCode = employeeCode,
            FirstName = firstName,
            LastName = lastName,
            Email = BuildAutoEmployeeEmail(employeeCode),
            HireDate = DateOnly.FromDateTime(now),
            DepartmentId = department.Id,
            PositionId = position.Id,
            Status = AutoCreatedEmployeeStatus,
            CreatedAtUtc = now,
            UpdatedAtUtc = now
        };

        dbContext.Employees.Add(employee);

        _logger.LogInformation(
            "Auto-created employee from VNTA Attendance Gateway payload. SourceLabel={SourceLabel}, EmployeeCode={EmployeeCode}, EmployeeId={EmployeeId}",
            sourceLabel,
            employee.EmployeeCode,
            employee.Id);

        return employee;
    }

    private async Task<ZktecoDepartment> EnsureFallbackDepartmentAsync(
        ZktecoDbContext dbContext,
        DateTime now,
        CancellationToken cancellationToken)
    {
        var trackedDepartment = dbContext.Departments.Local.FirstOrDefault(
            x => string.Equals(x.Code, UnassignedDepartmentCode, StringComparison.OrdinalIgnoreCase));
        if (trackedDepartment is not null)
        {
            return trackedDepartment;
        }

        var existingDepartments = await dbContext.Departments
            .Where(x => x.Code == UnassignedDepartmentCode)
            .OrderByDescending(x => x.UpdatedAtUtc ?? x.CreatedAtUtc)
            .ThenByDescending(x => x.CreatedAtUtc)
            .ThenByDescending(x => x.Id)
            .Take(2)
            .ToListAsync(cancellationToken);

        if (existingDepartments.Count > 1)
        {
            _logger.LogWarning(
                "Found duplicate fallback departments while resolving VNTA Attendance Gateway identity. DepartmentCode={DepartmentCode}, SelectedDepartmentId={DepartmentId}",
                UnassignedDepartmentCode,
                existingDepartments[0].Id);
        }

        if (existingDepartments.Count > 0)
        {
            return existingDepartments[0];
        }

        var department = new ZktecoDepartment
        {
            Id = Guid.CreateVersion7(),
            Code = UnassignedDepartmentCode,
            CenterName = UnassignedDepartmentName,
            DepartmentOrWorkshopName = UnassignedDepartmentName,
            Notes = "Tự động tạo để tiếp nhận nhân viên từ máy chấm công.",
            Status = AutoCreatedReferenceStatus,
            CreatedAtUtc = now,
            UpdatedAtUtc = now
        };

        dbContext.Departments.Add(department);

        _logger.LogInformation(
            "Auto-created fallback department for VNTA Attendance Gateway identity resolution. DepartmentCode={DepartmentCode}, DepartmentId={DepartmentId}",
            department.Code,
            department.Id);

        return department;
    }

    private async Task<ZktecoPosition> EnsureFallbackPositionAsync(
        ZktecoDbContext dbContext,
        DateTime now,
        CancellationToken cancellationToken)
    {
        var trackedPosition = dbContext.Positions.Local.FirstOrDefault(
            x => string.Equals(x.Code, UnassignedPositionCode, StringComparison.OrdinalIgnoreCase));
        if (trackedPosition is not null)
        {
            return trackedPosition;
        }

        var existingPositions = await dbContext.Positions
            .Where(x => x.Code == UnassignedPositionCode)
            .OrderByDescending(x => x.UpdatedAtUtc ?? x.CreatedAtUtc)
            .ThenByDescending(x => x.CreatedAtUtc)
            .ThenByDescending(x => x.Id)
            .Take(2)
            .ToListAsync(cancellationToken);

        if (existingPositions.Count > 1)
        {
            _logger.LogWarning(
                "Found duplicate fallback positions while resolving VNTA Attendance Gateway identity. PositionCode={PositionCode}, SelectedPositionId={PositionId}",
                UnassignedPositionCode,
                existingPositions[0].Id);
        }

        if (existingPositions.Count > 0)
        {
            return existingPositions[0];
        }

        var position = new ZktecoPosition
        {
            Id = Guid.CreateVersion7(),
            Code = UnassignedPositionCode,
            Name = UnassignedPositionName,
            Description = "Tự động tạo để tiếp nhận nhân viên từ máy chấm công.",
            Status = AutoCreatedReferenceStatus,
            CreatedAtUtc = now,
            UpdatedAtUtc = now
        };

        dbContext.Positions.Add(position);

        _logger.LogInformation(
            "Auto-created fallback position for VNTA Attendance Gateway identity resolution. PositionCode={PositionCode}, PositionId={PositionId}",
            position.Code,
            position.Id);

        return position;
    }

    private void UpdateEmployeeNameIfNeeded(ZktecoEmployee employee, string? fullName, string sourceLabel, DateTime now)
    {
        if (string.IsNullOrWhiteSpace(fullName))
        {
            return;
        }

        if (string.Equals(employee.FirstName, employee.EmployeeCode, StringComparison.OrdinalIgnoreCase) ||
            AutoGeneratedLastNames.Any(x => string.Equals(employee.LastName, x, StringComparison.OrdinalIgnoreCase)))
        {
            var (firstName, lastName) = SplitEmployeeName(fullName, employee.EmployeeCode, sourceLabel);
            employee.FirstName = firstName;
            employee.LastName = lastName;
            employee.UpdatedAtUtc = now;
        }
    }

    private static (string FirstName, string LastName) SplitEmployeeName(string? fullName, string fallbackEmployeeCode, string sourceLabel)
    {
        if (string.IsNullOrWhiteSpace(fullName))
        {
            return (fallbackEmployeeCode, BuildAutoLastName(sourceLabel));
        }

        var parts = fullName
            .Trim()
            .Split(' ', StringSplitOptions.RemoveEmptyEntries);

        if (parts.Length == 1)
        {
            return (parts[0], BuildAutoLastName(sourceLabel));
        }

        return (parts[^1], string.Join(' ', parts[..^1]));
    }

    private static string BuildAutoEmployeeEmail(string employeeCode)
    {
        var sanitized = new string(employeeCode
            .Trim()
            .ToLowerInvariant()
            .Select(ch => char.IsLetterOrDigit(ch) ? ch : '-')
            .ToArray());

        if (string.IsNullOrWhiteSpace(sanitized))
        {
            sanitized = "unknown";
        }

        return $"{sanitized}@autogen.VNTA.local";
    }

    private static string BuildAutoLastName(string sourceLabel)
    {
        return sourceLabel switch
        {
            "ATTLOG" => "Tự động từ ATTLOG",
            "OPERLOG" => "Tự động từ OPERLOG",
            "BIODATA" => "Tự động từ BIODATA",
            _ => "-"
        };
    }

    private sealed class ExistingEmployeeCandidate
    {
        public Guid Id { get; init; }

        public string EmployeeCode { get; init; } = string.Empty;

        public string FirstName { get; init; } = string.Empty;

        public string LastName { get; init; } = string.Empty;

        public string? Email { get; init; }

        public string? PhoneNumber { get; init; }

        public DateOnly HireDate { get; init; }

        public Guid DepartmentId { get; init; }

        public Guid PositionId { get; init; }

        public int Status { get; init; }

        public DateTime CreatedAtUtc { get; init; }

        public DateTime? UpdatedAtUtc { get; init; }
    }
}
