using System.Text;
using Vnta.AttendanceGateway.Data;
using Vnta.AttendanceGateway.Domain;
using Vnta.AttendanceGateway.Protocol.Parsers;
using Microsoft.EntityFrameworkCore;

namespace Vnta.AttendanceGateway.Integration;

public sealed class ErrorLogSyncService
{
    private static volatile bool _errorLogTableEnsured;
    private readonly IServiceScopeFactory _scopeFactory;
    private readonly ILogger<ErrorLogSyncService> _logger;

    public ErrorLogSyncService(IServiceScopeFactory scopeFactory, ILogger<ErrorLogSyncService> logger)
    {
        _scopeFactory = scopeFactory;
        _logger = logger;
    }

    public async Task<ErrorLogSyncResult> ProcessAsync(
        string deviceSn,
        string url,
        string rawBody,
        string? flowId,
        CancellationToken cancellationToken)
    {
        var receivedLines = AttendanceLogBodyParser.SplitLines(rawBody);
        using var scope = _scopeFactory.CreateScope();
        var dbContext = scope.ServiceProvider.GetRequiredService<ZktecoDbContext>();
        var normalizedSerial = deviceSn.Trim().ToUpperInvariant();

        var device = await dbContext.Devices
            .SingleOrDefaultAsync(x => x.SerialNumber == normalizedSerial, cancellationToken);

        if (device is null)
        {
            _logger.LogWarning("Attendance Gateway FLOW DB [{FlowId}] Could not resolve ERRORLOG device in database. DeviceSn={DeviceSn}", flowId ?? "<none>", normalizedSerial);
            return new ErrorLogSyncResult(receivedLines.Count, 0, false, null);
        }

        var stamp = HeaderParser.ExtractQueryParam(url, "Stamp");
        if (!string.IsNullOrWhiteSpace(stamp))
        {
            device.ErrorLogStamp = stamp.Trim();
            device.UpdatedAtUtc = VietnamTime.Now.DateTime;
        }

        await EnsureErrorLogTableExistsAsync(dbContext, cancellationToken);

        var savedLines = 0;
        foreach (var rawLine in receivedLines)
        {
            if (string.IsNullOrWhiteSpace(rawLine))
            {
                continue;
            }

            var errorLog = ParseErrorLogLine(rawLine, normalizedSerial);
            if (errorLog is null)
            {
                continue;
            }

            dbContext.ErrorLogs.Add(errorLog);
            savedLines++;
        }

        await dbContext.SaveChangesAsync(cancellationToken);

        _logger.LogInformation(
            "Attendance Gateway FLOW DB [{FlowId}] Processed ERRORLOG payload. DeviceSn={DeviceSn}, ReceivedLines={ReceivedLines}, SavedLines={SavedLines}, Stamp={Stamp}",
            flowId ?? "<none>",
            normalizedSerial,
            receivedLines.Count,
            savedLines,
            string.IsNullOrWhiteSpace(stamp) ? "<empty>" : stamp.Trim());

        return new ErrorLogSyncResult(receivedLines.Count, savedLines, true, string.IsNullOrWhiteSpace(stamp) ? null : stamp.Trim());
    }

    private async Task EnsureErrorLogTableExistsAsync(ZktecoDbContext dbContext, CancellationToken cancellationToken)
    {
        if (_errorLogTableEnsured)
        {
            return;
        }

        await dbContext.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS errorlog (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "ErrCode" text NULL,
                "ErrMsg" text NULL,
                "DataOrigin" text NULL,
                "CmdId" character varying(100) NULL,
                "Additional" text NULL,
                "DeviceId" character varying(50) NULL
            );
            """,
            cancellationToken);

        await dbContext.Database.ExecuteSqlRawAsync("""CREATE INDEX IF NOT EXISTS "IX_errorlog_DeviceId" ON errorlog ("DeviceId");""", cancellationToken);
        await dbContext.Database.ExecuteSqlRawAsync("""CREATE INDEX IF NOT EXISTS "IX_errorlog_CmdId" ON errorlog ("CmdId");""", cancellationToken);

        _errorLogTableEnsured = true;
        _logger.LogInformation("Ensured PostgreSQL table for ERRORLOG processing exists before ingesting payloads.");
    }

    private ZktecoErrorLog? ParseErrorLogLine(string rawLine, string deviceSn)
    {
        if (!GetLineToken(rawLine).Equals("ERRORLOG", StringComparison.OrdinalIgnoreCase))
        {
            return null;
        }

        var values = ParseKeyValuesAfterPrefix(rawLine, "ERRORLOG");
        if (values.Count == 0)
        {
            _logger.LogWarning(
                "Skipping ERRORLOG line because it does not contain valid key-value pairs. DeviceSn={DeviceSn}, RawLine={RawLine}",
                deviceSn,
                rawLine);
            return null;
        }

        return new ZktecoErrorLog
        {
            ErrCode = GetValue(values, "ERRCODE"),
            ErrMsg = GetValue(values, "ERRMSG"),
            DataOrigin = GetValue(values, "DATAORIGIN"),
            CmdId = GetValue(values, "CMDID"),
            Additional = GetValue(values, "ADDITIONAL"),
            DeviceId = deviceSn
        };
    }

    private static Dictionary<string, string> ParseKeyValuesAfterPrefix(string rawLine, string prefix)
    {
        var payload = rawLine.Length > prefix.Length
            ? rawLine[prefix.Length..].Trim()
            : string.Empty;

        var result = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        foreach (var segment in payload.Split('\t', StringSplitOptions.RemoveEmptyEntries))
        {
            var delimiterIndex = segment.IndexOf('=');
            if (delimiterIndex <= 0)
            {
                continue;
            }

            var key = segment[..delimiterIndex].Trim().ToUpperInvariant();
            var value = segment[(delimiterIndex + 1)..].Trim();
            if (!string.IsNullOrWhiteSpace(key))
            {
                result[key] = value;
            }
        }

        return result;
    }

    private static string GetLineToken(string rawLine)
    {
        if (string.IsNullOrWhiteSpace(rawLine))
        {
            return string.Empty;
        }

        var trimmed = rawLine.TrimStart();
        var tokenBuilder = new StringBuilder();
        foreach (var ch in trimmed)
        {
            if (char.IsWhiteSpace(ch))
            {
                break;
            }

            tokenBuilder.Append(char.ToUpperInvariant(ch));
        }

        return tokenBuilder.ToString();
    }

    private static string? GetValue(IReadOnlyDictionary<string, string> values, string key)
        => values.TryGetValue(key, out var value) ? value : null;
}

public sealed record ErrorLogSyncResult(int ReceivedLineCount, int SavedLineCount, bool DeviceResolved, string? Stamp);
