using System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Npgsql;
using Vnta.Hrm.Infrastructure.Data;

namespace Vnta.Hrm.Infrastructure.NhanSu.NhanVien;

public sealed class DatabaseEmployeeRefreshService(
    ApplicationDbContext dbContext,
    ILogger<DatabaseEmployeeRefreshService> logger)
    : IEmployeeRefreshService, INhanVienRefreshService
{
    private const string DeviceUserProfilesLogicalTableName = "device_user_profiles";
    private const string UnassignedDepartmentName = "Phòng ban chưa đặt tên";
    private const string UnassignedDepartmentCode = "AUTO-UNASSIGNED-DEPARTMENT";
    private const string UnassignedPositionName = "Chưa xác định chức vụ";
    private const string UnassignedPositionCode = "AUTO-UNASSIGNED-POSITION";
    private const int ActiveEmployeeStatus = 2;
    private const int DefaultReferenceStatus = 0;

    private static readonly string[] EmployeeCodeColumns = ["badgenumber", "badge_number", "employeecode", "employee_code", "empcode", "emp_code", "workno", "work_no", "cardno", "card_no"];
    private static readonly string[] UserIdColumns = ["userid", "user_id", "pin", "pin2", "id"];
    private static readonly string[] FullNameColumns = ["name", "fullname", "full_name", "user_name", "username"];
    private static readonly string[] UpdatedAtColumns = ["updatedatutc", "updated_at_utc", "updatedat", "updated_at"];
    private static readonly string[] CreatedAtColumns = ["createdatutc", "created_at_utc", "createdat", "created_at"];
    private static readonly string[] AutoGeneratedLastNames =
    [
        "Tự động từ ATTLOG",
        "Tự động từ OPERLOG",
        "Tự động từ BIODATA",
        "Tự động từ hồ sơ máy chấm công",
        "-"
    ];

    public async Task<EmployeeRefreshResult> RefreshFromDeviceUserProfilesAsync(CancellationToken cancellationToken = default)
    {
        cancellationToken.ThrowIfCancellationRequested();

        var connection = (NpgsqlConnection)dbContext.Database.GetDbConnection();
        var shouldCloseConnection = connection.State != ConnectionState.Open;
        if (shouldCloseConnection)
        {
            await connection.OpenAsync(cancellationToken);
        }

        try
        {
            var metadata = await ResolveDeviceUserProfileMetadataAsync(connection, cancellationToken);
            if (metadata is null)
            {
                logger.LogWarning("Không tìm thấy schema bảng device_user_profiles phù hợp để đồng bộ nhân viên.");
                return new EmployeeRefreshResult(
                    false,
                    0,
                    0,
                    0,
                    0,
                    NormalizeDatabaseTimestamp(DateTime.UtcNow),
                    "Không tìm thấy bảng device_user_profiles hợp lệ để đồng bộ.");
            }

            var sourceUsers = await LoadDeviceUserProfileRowsAsync(connection, metadata, cancellationToken);
            if (sourceUsers.Count == 0)
            {
                return new EmployeeRefreshResult(
                    true,
                    0,
                    0,
                    0,
                    0,
                    NormalizeDatabaseTimestamp(DateTime.UtcNow),
                    "Bảng device_user_profiles hiện chưa có dữ liệu hợp lệ.");
            }

            var normalizedCodesLower = sourceUsers
                .Select(static user => user.EmployeeCode.ToLowerInvariant())
                .Distinct(StringComparer.Ordinal)
                .ToArray();

            var existingEmployees = await dbContext.Employees
                .Where(employee => normalizedCodesLower.Contains(employee.EmployeeCode.ToLower()))
                .OrderByDescending(employee => !employee.IsDeleted)
                .ThenByDescending(employee => employee.UpdatedAtUtc ?? employee.CreatedAtUtc)
                .ThenByDescending(employee => employee.CreatedAtUtc)
                .ThenByDescending(employee => employee.Id)
                .ToListAsync(cancellationToken);

            var existingEmployeesByCode = existingEmployees
                .GroupBy(static employee => NormalizeEmployeeCode(employee.EmployeeCode), StringComparer.OrdinalIgnoreCase)
                .ToDictionary(static group => group.Key, static group => group.ToArray(), StringComparer.OrdinalIgnoreCase);

            AttendanceDepartmentRow? fallbackDepartment = null;
            AttendanceGatewayPositionRow? fallbackPosition = null;
            var createdCount = 0;
            var updatedCount = 0;
            var skippedCount = 0;
            var now = NormalizeDatabaseTimestamp(DateTime.UtcNow);

            foreach (var sourceUser in sourceUsers)
            {
                cancellationToken.ThrowIfCancellationRequested();

                if (!existingEmployeesByCode.TryGetValue(sourceUser.EmployeeCode, out var matchedEmployees))
                {
                    fallbackDepartment ??= await EnsureFallbackDepartmentAsync(now, cancellationToken);
                    fallbackPosition ??= await EnsureFallbackPositionAsync(now, cancellationToken);

                    var (lastName, firstName) = SplitFullName(sourceUser.FullName, sourceUser.EmployeeCode);
                    dbContext.Employees.Add(new AttendanceGatewayEmployeeRow
                    {
                        Id = Guid.CreateVersion7(),
                        EmployeeCode = sourceUser.EmployeeCode,
                        FirstName = firstName,
                        LastName = lastName,
                        Email = BuildAutoEmployeeEmail(sourceUser.EmployeeCode),
                        HireDate = now.Date,
                        DepartmentId = fallbackDepartment.Id,
                        PositionId = fallbackPosition.Id,
                        Status = ActiveEmployeeStatus,
                        CreatedAtUtc = now,
                        UpdatedAtUtc = now,
                        IsDeleted = false
                    });
                    createdCount++;
                    continue;
                }

                var activeEmployee = matchedEmployees.FirstOrDefault(static employee => !employee.IsDeleted);
                if (activeEmployee is null)
                {
                    skippedCount++;
                    logger.LogInformation(
                        "Bỏ qua mã nhân viên {EmployeeCode} từ device_user_profiles vì chỉ tìm thấy bản ghi đã xóa mềm trong employees.",
                        sourceUser.EmployeeCode);
                    continue;
                }

                if (matchedEmployees.Count(static employee => !employee.IsDeleted) > 1)
                {
                    logger.LogWarning(
                        "Phát hiện nhiều bản ghi employees đang hoạt động cùng mã {EmployeeCode}; chọn bản ghi mới nhất để cập nhật.",
                        sourceUser.EmployeeCode);
                }

                var changed = false;
                if (ShouldUpdateEmployeeName(activeEmployee, sourceUser.FullName))
                {
                    var (lastName, firstName) = SplitFullName(sourceUser.FullName, sourceUser.EmployeeCode);
                    if (!string.Equals(activeEmployee.FirstName, firstName, StringComparison.Ordinal) ||
                        !string.Equals(activeEmployee.LastName, lastName, StringComparison.Ordinal))
                    {
                        activeEmployee.FirstName = firstName;
                        activeEmployee.LastName = lastName;
                        changed = true;
                    }
                }

                if (string.IsNullOrWhiteSpace(activeEmployee.Email))
                {
                    activeEmployee.Email = BuildAutoEmployeeEmail(sourceUser.EmployeeCode);
                    changed = true;
                }

                if (changed)
                {
                    activeEmployee.UpdatedAtUtc = now;
                    updatedCount++;
                }
                else
                {
                    skippedCount++;
                }
            }

            await dbContext.SaveChangesAsync(cancellationToken);

            logger.LogInformation(
                "Đã đồng bộ nhân viên từ device_user_profiles. SourceRows={SourceRows}, Created={Created}, Updated={Updated}, Skipped={Skipped}",
                sourceUsers.Count,
                createdCount,
                updatedCount,
                skippedCount);

            return new EmployeeRefreshResult(
                true,
                sourceUsers.Count,
                createdCount,
                updatedCount,
                skippedCount,
                now,
                null);
        }
        finally
        {
            if (shouldCloseConnection)
            {
                await connection.CloseAsync();
            }
        }
    }

    private async Task<AttendanceDepartmentRow> EnsureFallbackDepartmentAsync(
        DateTime now,
        CancellationToken cancellationToken)
    {
        var trackedDepartment = dbContext.Departments.Local.FirstOrDefault(
            row => string.Equals(row.Code, UnassignedDepartmentCode, StringComparison.OrdinalIgnoreCase));
        if (trackedDepartment is not null)
        {
            return trackedDepartment;
        }

        var existingDepartment = await dbContext.Departments
            .OrderByDescending(row => row.UpdatedAtUtc ?? row.CreatedAtUtc)
            .ThenByDescending(row => row.CreatedAtUtc)
            .ThenByDescending(row => row.Id)
            .FirstOrDefaultAsync(
                row => row.Code.ToLower() == UnassignedDepartmentCode.ToLower(),
                cancellationToken);
        if (existingDepartment is not null)
        {
            return existingDepartment;
        }

        var department = new AttendanceDepartmentRow
        {
            Id = Guid.CreateVersion7(),
            Code = UnassignedDepartmentCode,
            CenterName = UnassignedDepartmentName,
            DepartmentOrWorkshopName = UnassignedDepartmentName,
            Notes = "Tự động tạo khi đồng bộ nhân viên từ device_user_profiles.",
            Status = DefaultReferenceStatus,
            CreatedAtUtc = now,
            UpdatedAtUtc = now
        };

        dbContext.Departments.Add(department);
        return department;
    }

    private async Task<AttendanceGatewayPositionRow> EnsureFallbackPositionAsync(
        DateTime now,
        CancellationToken cancellationToken)
    {
        var trackedPosition = dbContext.Positions.Local.FirstOrDefault(
            row => string.Equals(row.Code, UnassignedPositionCode, StringComparison.OrdinalIgnoreCase));
        if (trackedPosition is not null)
        {
            return trackedPosition;
        }

        var existingPosition = await dbContext.Positions
            .OrderByDescending(row => row.UpdatedAtUtc ?? row.CreatedAtUtc)
            .ThenByDescending(row => row.CreatedAtUtc)
            .ThenByDescending(row => row.Id)
            .FirstOrDefaultAsync(
                row => row.Code.ToLower() == UnassignedPositionCode.ToLower(),
                cancellationToken);
        if (existingPosition is not null)
        {
            return existingPosition;
        }

        var position = new AttendanceGatewayPositionRow
        {
            Id = Guid.CreateVersion7(),
            Code = UnassignedPositionCode,
            Name = UnassignedPositionName,
            Description = "Tự động tạo khi đồng bộ nhân viên từ device_user_profiles.",
            Status = DefaultReferenceStatus,
            EmployeeCount = 0,
            CreatedAtUtc = now,
            UpdatedAtUtc = now
        };

        dbContext.Positions.Add(position);
        return position;
    }

    private static bool ShouldUpdateEmployeeName(AttendanceGatewayEmployeeRow employee, string? sourceFullName)
    {
        if (string.IsNullOrWhiteSpace(sourceFullName))
        {
            return false;
        }

        if (string.IsNullOrWhiteSpace(employee.FirstName) || string.IsNullOrWhiteSpace(employee.LastName))
        {
            return true;
        }

        if (string.Equals(employee.FirstName, employee.EmployeeCode, StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        return AutoGeneratedLastNames.Any(
            autoName => string.Equals(employee.LastName, autoName, StringComparison.OrdinalIgnoreCase));
    }

    private static (string LastName, string FirstName) SplitFullName(string? fullName, string employeeCode)
    {
        if (string.IsNullOrWhiteSpace(fullName))
        {
            return ("Tự động từ hồ sơ máy chấm công", employeeCode);
        }

        var parts = fullName
            .Trim()
            .Split(' ', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);

        return parts.Length switch
        {
            0 => ("Tự động từ hồ sơ máy chấm công", employeeCode),
            1 => ("Tự động từ hồ sơ máy chấm công", parts[0]),
            _ => (string.Join(' ', parts[..^1]), parts[^1])
        };
    }

    private static string BuildAutoEmployeeEmail(string employeeCode)
    {
        var sanitized = new string(employeeCode
            .Trim()
            .ToLowerInvariant()
            .Select(static ch => char.IsLetterOrDigit(ch) ? ch : '-')
            .ToArray());

        if (string.IsNullOrWhiteSpace(sanitized))
        {
            sanitized = "unknown";
        }

        return $"{sanitized}@autogen.VNTA.local";
    }

    private static string NormalizeEmployeeCode(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return string.Empty;
        }

        return EmployeeCodeNormalizer.Normalize(value) ?? string.Empty;
    }

    private static DateTime NormalizeDatabaseTimestamp(DateTime value) =>
        value.Kind == DateTimeKind.Unspecified
            ? value
            : DateTime.SpecifyKind(value, DateTimeKind.Unspecified);

    private static async Task<DeviceUserProfileMetadata?> ResolveDeviceUserProfileMetadataAsync(
        NpgsqlConnection connection,
        CancellationToken cancellationToken)
    {
        var resolvedTable = await ResolveTableNameAsync(connection, DeviceUserProfilesLogicalTableName, cancellationToken);
        if (resolvedTable is null)
        {
            return null;
        }

        var columns = await GetColumnNamesAsync(connection, resolvedTable, cancellationToken);
        var employeeCodeColumn = PickFirst(columns, EmployeeCodeColumns);
        var userIdColumn = PickFirst(columns, UserIdColumns);
        if (employeeCodeColumn is null)
        {
            return null;
        }

        return new DeviceUserProfileMetadata(
            resolvedTable,
            employeeCodeColumn,
            userIdColumn,
            PickFirst(columns, FullNameColumns),
            PickFirst(columns, UpdatedAtColumns),
            PickFirst(columns, CreatedAtColumns));
    }

    private static async Task<List<DeviceUserProfileSourceRow>> LoadDeviceUserProfileRowsAsync(
        NpgsqlConnection connection,
        DeviceUserProfileMetadata metadata,
        CancellationToken cancellationToken)
    {
        var sql = $"""
            select
                cast({QuoteIdentifier(metadata.EmployeeCodeColumn)} as text) as employee_code,
                {BuildNullableTextProjection(metadata.UserIdColumn, "user_id")},
                {BuildNullableTextProjection(metadata.FullNameColumn, "full_name")},
                {BuildNullableTimestampProjection(metadata.UpdatedAtColumn, "updated_at")},
                {BuildNullableTimestampProjection(metadata.CreatedAtColumn, "created_at")}
            from {QuoteIdentifier(metadata.TableName)}
            where nullif(btrim(cast({QuoteIdentifier(metadata.EmployeeCodeColumn)} as text)), '') is not null
            """;

        var rows = new List<DeviceUserProfileSourceRow>();
        await using var command = new NpgsqlCommand(sql, connection);
        await using var reader = await command.ExecuteReaderAsync(CommandBehavior.SequentialAccess, cancellationToken);
        while (await reader.ReadAsync(cancellationToken))
        {
            if (reader.IsDBNull(0))
            {
                continue;
            }

            var normalizedEmployeeCode = NormalizeEmployeeCode(reader.GetString(0));
            if (string.IsNullOrWhiteSpace(normalizedEmployeeCode))
            {
                continue;
            }

            var userId = reader.IsDBNull(1) ? null : reader.GetString(1)?.Trim();
            var fullName = reader.IsDBNull(2) ? null : reader.GetString(2)?.Trim();
            DateTime? updatedAt = reader.IsDBNull(3) ? null : reader.GetDateTime(3);
            DateTime? createdAt = reader.IsDBNull(4) ? null : reader.GetDateTime(4);

            rows.Add(new DeviceUserProfileSourceRow(
                normalizedEmployeeCode,
                userId,
                fullName,
                updatedAt,
                createdAt));
        }

        return rows
            .GroupBy(static row => row.EmployeeCode, StringComparer.OrdinalIgnoreCase)
            .Select(static group => group
                .OrderByDescending(row => row.UpdatedAt ?? row.CreatedAt)
                .ThenByDescending(row => row.CreatedAt)
                .ThenByDescending(row => row.UserId)
                .First())
            .OrderBy(static row => row.EmployeeCode, StringComparer.OrdinalIgnoreCase)
            .ToList();
    }

    private static async Task<string?> ResolveTableNameAsync(
        NpgsqlConnection connection,
        string expectedTableName,
        CancellationToken cancellationToken)
    {
        const string sql = """
            select table_name
            from information_schema.tables
            where table_schema not in ('pg_catalog', 'information_schema')
              and lower(table_name) = @tableName
            limit 1
            """;

        await using var command = new NpgsqlCommand(sql, connection);
        command.Parameters.AddWithValue("tableName", expectedTableName.ToLowerInvariant());
        var result = await command.ExecuteScalarAsync(cancellationToken);
        return result as string;
    }

    private static async Task<Dictionary<string, string>> GetColumnNamesAsync(
        NpgsqlConnection connection,
        string tableName,
        CancellationToken cancellationToken)
    {
        const string sql = """
            select column_name
            from information_schema.columns
            where table_schema not in ('pg_catalog', 'information_schema')
              and lower(table_name) = @tableName
            """;

        await using var command = new NpgsqlCommand(sql, connection);
        command.Parameters.AddWithValue("tableName", tableName.ToLowerInvariant());

        var result = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        await using var reader = await command.ExecuteReaderAsync(CommandBehavior.SequentialAccess, cancellationToken);
        while (await reader.ReadAsync(cancellationToken))
        {
            if (reader.IsDBNull(0))
            {
                continue;
            }

            var columnName = reader.GetString(0);
            result[columnName.ToLowerInvariant()] = columnName;
        }

        return result;
    }

    private static string? PickFirst(
        IReadOnlyDictionary<string, string> columns,
        IEnumerable<string> candidates)
    {
        foreach (var candidate in candidates)
        {
            if (columns.TryGetValue(candidate.ToLowerInvariant(), out var actualColumnName))
            {
                return actualColumnName;
            }
        }

        return null;
    }

    private static string BuildNullableTextProjection(
        string? columnName,
        string alias)
    {
        if (columnName is null)
        {
            return $"null::text as {alias}";
        }

        return $"cast({QuoteIdentifier(columnName)} as text) as {alias}";
    }

    private static string BuildNullableTimestampProjection(
        string? columnName,
        string alias)
    {
        if (columnName is null)
        {
            return $"null::timestamp as {alias}";
        }

        return $"cast({QuoteIdentifier(columnName)} as timestamp) as {alias}";
    }

    private static string QuoteIdentifier(string identifier) =>
        "\"" + identifier.Replace("\"", "\"\"", StringComparison.Ordinal) + "\"";

    private sealed record DeviceUserProfileMetadata(
        string TableName,
        string EmployeeCodeColumn,
        string? UserIdColumn,
        string? FullNameColumn,
        string? UpdatedAtColumn,
        string? CreatedAtColumn);

    private sealed record DeviceUserProfileSourceRow(
        string EmployeeCode,
        string? UserId,
        string? FullName,
        DateTime? UpdatedAt,
        DateTime? CreatedAt);
}
